packages:
  - 'apps/*'
  - 'libs/*'
  - 'libs/*/*'
autoInstallPeers: true
onlyBuiltDependencies:
  - nx
  - '@swc/core'
  - '@nestjs/core'
  - esbuild
  - unrs-resolver
  - '@prisma/engines'
  - '@prisma/client'
  - prisma
