#!/usr/bin/env node
'use strict';

/**
 * Generate OpenAPI 3 JSON+YAML for each Nest service from live /docs-json.
 *
 *   pnpm openapi:generate
 *   OPENAPI_REQUIRE_LIVE=1 pnpm openapi:generate
 */
const fs = require('fs');
const path = require('path');
const { SERVICES, OPENAPI_DIR_NAME } = require('./catalog.cjs');
const { dumpYaml, normalizeOpenApiDocument } = require('./yaml.cjs');

const root = path.resolve(__dirname, '../..');
const outDir = path.join(root, OPENAPI_DIR_NAME);
const requireLive = process.env.OPENAPI_REQUIRE_LIVE === '1';

async function fetchDocsJson(port) {
  const url = `http://127.0.0.1:${port}/docs-json`;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 8_000);
  try {
    const res = await fetch(url, { signal: controller.signal });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return await res.json();
  } finally {
    clearTimeout(timer);
  }
}

function skeletonDocument(service) {
  return {
    openapi: '3.0.3',
    info: {
      title: service.title,
      description: `${service.description}\n\nSkeleton — service offline. Re-run with live stack.`,
      version: '1.0.0',
    },
    paths: {},
  };
}

async function main() {
  fs.mkdirSync(outDir, { recursive: true });
  let liveCount = 0;

  for (const service of SERVICES) {
    let source = 'live';
    let doc;
    try {
      doc = await fetchDocsJson(service.port);
      liveCount += 1;
    } catch (err) {
      if (requireLive) {
        console.error(
          `[openapi:generate] FAIL ${service.id}: ${err.message || err}`,
        );
        process.exit(1);
      }
      source = 'skeleton';
      doc = skeletonDocument(service);
      console.warn(
        `[openapi:generate] WARN ${service.id} unreachable — skeleton (${err.message || err})`,
      );
    }

    const normalized = normalizeOpenApiDocument(doc, service);
    const base = `${service.id}.openapi`;
    const jsonPath = path.join(outDir, `${base}.json`);
    const yamlPath = path.join(outDir, `${base}.yaml`);
    fs.writeFileSync(
      jsonPath,
      `${JSON.stringify(normalized, null, 2)}\n`,
      'utf8',
    );
    fs.writeFileSync(
      yamlPath,
      `# Generated by pnpm openapi:generate — no secrets.\n# service: ${service.id}\n# source: ${source}\n${dumpYaml(normalized)}\n`,
      'utf8',
    );
    console.log(
      `[openapi:generate] ${service.id} paths=${Object.keys(normalized.paths || {}).length} source=${source}`,
    );
  }

  console.log(
    `[openapi:generate] done: ${SERVICES.length} services (${liveCount} live). Run: pnpm openapi:combine && pnpm openapi:validate`,
  );
}

main().catch((err) => {
  console.error('[openapi:generate] FATAL:', err);
  process.exit(1);
});
