#!/usr/bin/env node
'use strict';

/**
 * Interactive setup for Security Exploit Guide credentials.
 * Writes gitignored `.env.security-guide.local` — never logs plaintext password.
 *
 *   pnpm security-guide:setup
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const readline = require('readline');
const bcrypt = require('bcryptjs');

const root = path.resolve(__dirname, '../..');
const outFile = path.join(root, '.env.security-guide.local');

function ask(rl, question, { silent = false } = {}) {
  return new Promise((resolve) => {
    if (!silent) {
      rl.question(question, resolve);
      return;
    }
    const stdin = process.stdin;
    const onData = (char) => {
      char = char.toString();
      switch (char) {
        case '\n':
        case '\r':
        case '\u0004':
          stdin.removeListener('data', onData);
          process.stdout.write('\n');
          break;
        case '\u0003':
          process.exit(1);
          break;
        default:
          process.stdout.write('*');
          break;
      }
    };
    process.stdout.write(question);
    stdin.on('data', onData);
    rl.question('', (answer) => {
      stdin.removeListener('data', onData);
      resolve(answer);
    });
  });
}

async function main() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  console.log('NexaTech Security Guide credential setup');
  console.log('Credentials are local-only and never committed.\n');

  const username = (await ask(rl, 'Username: ')).trim();
  if (!username || username.length < 3) {
    console.error('Username must be at least 3 characters.');
    process.exit(1);
  }

  const password = await ask(rl, 'Password: ', { silent: true });
  const confirm = await ask(rl, 'Confirm password: ', { silent: true });
  rl.close();

  if (!password || password.length < 12) {
    console.error('Password must be at least 12 characters.');
    process.exit(1);
  }
  if (password !== confirm) {
    console.error('Passwords do not match.');
    process.exit(1);
  }

  const hash = await bcrypt.hash(password, 12);
  const sessionSecret = crypto.randomBytes(48).toString('base64url');
  const ttl = process.env.SECURITY_GUIDE_SESSION_TTL_SECONDS || '28800';

  const body = [
    '# Generated by pnpm security-guide:setup — DO NOT COMMIT',
    `SECURITY_GUIDE_USERNAME=${username}`,
    `SECURITY_GUIDE_PASSWORD_HASH=${hash}`,
    `SECURITY_GUIDE_SESSION_SECRET=${sessionSecret}`,
    `SECURITY_GUIDE_SESSION_TTL_SECONDS=${ttl}`,
    '',
  ].join('\n');

  fs.writeFileSync(outFile, body, { encoding: 'utf8', mode: 0o600 });
  console.log(`\nWrote ${path.relative(root, outFile)}`);
  console.log('Restart security-guide portal to apply.');
}

main().catch((err) => {
  console.error('Setup failed:', err.message || err);
  process.exit(1);
});
