export type ErrorDetails = Record<string, unknown>;

export interface ErrorEnvelope {
  errorCode: string;
  message: string;
  details: ErrorDetails;
  traceId: string;
  timestamp: string;
}

export const ErrorCodes = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  CATALOG_PRODUCT_NOT_FOUND: 'CATALOG_PRODUCT_NOT_FOUND',
  CATALOG_CATEGORY_NOT_FOUND: 'CATALOG_CATEGORY_NOT_FOUND',
  CATALOG_BRAND_NOT_FOUND: 'CATALOG_BRAND_NOT_FOUND',
  CATALOG_SKU_NOT_FOUND: 'CATALOG_SKU_NOT_FOUND',
  CATALOG_SLUG_CONFLICT: 'CATALOG_SLUG_CONFLICT',
  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
  MEDIA_FORBIDDEN: 'MEDIA_FORBIDDEN',
  MEDIA_INVALID_TYPE: 'MEDIA_INVALID_TYPE',
  MEDIA_TOO_LARGE: 'MEDIA_TOO_LARGE',
  INVENTORY_NOT_FOUND: 'INVENTORY_NOT_FOUND',
  INVENTORY_INSUFFICIENT: 'INVENTORY_INSUFFICIENT',
  INVENTORY_CONFLICT: 'INVENTORY_CONFLICT',
  INVENTORY_IDEMPOTENCY_CONFLICT: 'INVENTORY_IDEMPOTENCY_CONFLICT',
  INVENTORY_RESERVATION_NOT_FOUND: 'INVENTORY_RESERVATION_NOT_FOUND',
  INVENTORY_TRANSFER_INVALID: 'INVENTORY_TRANSFER_INVALID',
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  CART_FORBIDDEN: 'CART_FORBIDDEN',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  CART_SKU_UNAVAILABLE: 'CART_SKU_UNAVAILABLE',
  CART_QUANTITY_INVALID: 'CART_QUANTITY_INVALID',
  CART_QUANTITY_LIMIT: 'CART_QUANTITY_LIMIT',
  CART_CONFLICT: 'CART_CONFLICT',
  CART_IDEMPOTENCY_CONFLICT: 'CART_IDEMPOTENCY_CONFLICT',
  CART_EXPIRED: 'CART_EXPIRED',
  CART_MERGE_INVALID: 'CART_MERGE_INVALID',
  CART_INVENTORY_UNAVAILABLE: 'CART_INVENTORY_UNAVAILABLE',
  CART_CATALOG_UNAVAILABLE: 'CART_CATALOG_UNAVAILABLE',
  WISHLIST_LIMIT: 'WISHLIST_LIMIT',
  COMPARISON_LIMIT: 'COMPARISON_LIMIT',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_FORBIDDEN: 'ORDER_FORBIDDEN',
  ORDER_EMPTY_CART: 'ORDER_EMPTY_CART',
  ORDER_CART_INVALID: 'ORDER_CART_INVALID',
  ORDER_PRICE_CHANGED: 'ORDER_PRICE_CHANGED',
  ORDER_SKU_UNAVAILABLE: 'ORDER_SKU_UNAVAILABLE',
  ORDER_INSUFFICIENT_STOCK: 'ORDER_INSUFFICIENT_STOCK',
  ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',
  ORDER_CANCEL_NOT_ALLOWED: 'ORDER_CANCEL_NOT_ALLOWED',
  ORDER_CONFLICT: 'ORDER_CONFLICT',
  ORDER_IDEMPOTENCY_CONFLICT: 'ORDER_IDEMPOTENCY_CONFLICT',
  ORDER_RESERVATION_FAILED: 'ORDER_RESERVATION_FAILED',
  ORDER_CART_UNAVAILABLE: 'ORDER_CART_UNAVAILABLE',
  ORDER_CATALOG_UNAVAILABLE: 'ORDER_CATALOG_UNAVAILABLE',
  ORDER_INVENTORY_UNAVAILABLE: 'ORDER_INVENTORY_UNAVAILABLE',
  ORDER_ADDRESS_REQUIRED: 'ORDER_ADDRESS_REQUIRED',
  ORDER_ALREADY_CANCELLED: 'ORDER_ALREADY_CANCELLED',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_FORBIDDEN: 'PAYMENT_FORBIDDEN',
  PAYMENT_INVALID_METHOD: 'PAYMENT_INVALID_METHOD',
  PAYMENT_INVALID_STATUS: 'PAYMENT_INVALID_STATUS',
  PAYMENT_INVALID_TRANSITION: 'PAYMENT_INVALID_TRANSITION',
  PAYMENT_ALREADY_EXISTS: 'PAYMENT_ALREADY_EXISTS',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',
  PAYMENT_CONFLICT: 'PAYMENT_CONFLICT',
  PAYMENT_IDEMPOTENCY_CONFLICT: 'PAYMENT_IDEMPOTENCY_CONFLICT',
  PAYMENT_SIGNATURE_INVALID: 'PAYMENT_SIGNATURE_INVALID',
  PAYMENT_CALLBACK_INVALID: 'PAYMENT_CALLBACK_INVALID',
  PAYMENT_PROVIDER_DISABLED: 'PAYMENT_PROVIDER_DISABLED',
  PAYMENT_ORDER_UNAVAILABLE: 'PAYMENT_ORDER_UNAVAILABLE',
  PAYMENT_ORDER_NOT_PAYABLE: 'PAYMENT_ORDER_NOT_PAYABLE',
  PAYMENT_REFUND_NOT_ALLOWED: 'PAYMENT_REFUND_NOT_ALLOWED',
  PAYMENT_REFUND_EXCEEDS_PAID: 'PAYMENT_REFUND_EXCEEDS_PAID',
  PAYMENT_REFUND_ALREADY_PROCESSED: 'PAYMENT_REFUND_ALREADY_PROCESSED',
  PAYMENT_MOCK_DISABLED: 'PAYMENT_MOCK_DISABLED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes] | string;

const HTTP_STATUS_BY_CODE: Record<string, number> = {
  [ErrorCodes.VALIDATION_FAILED]: 400,
  [ErrorCodes.BAD_REQUEST]: 400,
  [ErrorCodes.MEDIA_INVALID_TYPE]: 400,
  [ErrorCodes.MEDIA_TOO_LARGE]: 400,
  [ErrorCodes.UNAUTHORIZED]: 401,
  [ErrorCodes.FORBIDDEN]: 403,
  [ErrorCodes.MEDIA_FORBIDDEN]: 403,
  [ErrorCodes.NOT_FOUND]: 404,
  [ErrorCodes.CATALOG_PRODUCT_NOT_FOUND]: 404,
  [ErrorCodes.CATALOG_CATEGORY_NOT_FOUND]: 404,
  [ErrorCodes.CATALOG_BRAND_NOT_FOUND]: 404,
  [ErrorCodes.CATALOG_SKU_NOT_FOUND]: 404,
  [ErrorCodes.MEDIA_NOT_FOUND]: 404,
  [ErrorCodes.CONFLICT]: 409,
  [ErrorCodes.CATALOG_SLUG_CONFLICT]: 409,
  [ErrorCodes.INVENTORY_CONFLICT]: 409,
  [ErrorCodes.INVENTORY_IDEMPOTENCY_CONFLICT]: 409,
  [ErrorCodes.INVENTORY_INSUFFICIENT]: 409,
  [ErrorCodes.INVENTORY_TRANSFER_INVALID]: 400,
  [ErrorCodes.INVENTORY_NOT_FOUND]: 404,
  [ErrorCodes.INVENTORY_RESERVATION_NOT_FOUND]: 404,
  [ErrorCodes.CART_NOT_FOUND]: 404,
  [ErrorCodes.CART_ITEM_NOT_FOUND]: 404,
  [ErrorCodes.CART_FORBIDDEN]: 403,
  [ErrorCodes.CART_SKU_UNAVAILABLE]: 409,
  [ErrorCodes.CART_QUANTITY_INVALID]: 400,
  [ErrorCodes.CART_QUANTITY_LIMIT]: 400,
  [ErrorCodes.CART_CONFLICT]: 409,
  [ErrorCodes.CART_IDEMPOTENCY_CONFLICT]: 409,
  [ErrorCodes.CART_EXPIRED]: 410,
  [ErrorCodes.CART_MERGE_INVALID]: 400,
  [ErrorCodes.CART_INVENTORY_UNAVAILABLE]: 503,
  [ErrorCodes.CART_CATALOG_UNAVAILABLE]: 503,
  [ErrorCodes.WISHLIST_LIMIT]: 400,
  [ErrorCodes.COMPARISON_LIMIT]: 400,
  [ErrorCodes.ORDER_NOT_FOUND]: 404,
  [ErrorCodes.ORDER_FORBIDDEN]: 403,
  [ErrorCodes.ORDER_EMPTY_CART]: 400,
  [ErrorCodes.ORDER_CART_INVALID]: 409,
  [ErrorCodes.ORDER_PRICE_CHANGED]: 409,
  [ErrorCodes.ORDER_SKU_UNAVAILABLE]: 409,
  [ErrorCodes.ORDER_INSUFFICIENT_STOCK]: 409,
  [ErrorCodes.ORDER_INVALID_TRANSITION]: 409,
  [ErrorCodes.ORDER_CANCEL_NOT_ALLOWED]: 409,
  [ErrorCodes.ORDER_CONFLICT]: 409,
  [ErrorCodes.ORDER_IDEMPOTENCY_CONFLICT]: 409,
  [ErrorCodes.ORDER_RESERVATION_FAILED]: 409,
  [ErrorCodes.ORDER_CART_UNAVAILABLE]: 503,
  [ErrorCodes.ORDER_CATALOG_UNAVAILABLE]: 503,
  [ErrorCodes.ORDER_INVENTORY_UNAVAILABLE]: 503,
  [ErrorCodes.ORDER_ADDRESS_REQUIRED]: 400,
  [ErrorCodes.ORDER_ALREADY_CANCELLED]: 409,
  [ErrorCodes.PAYMENT_NOT_FOUND]: 404,
  [ErrorCodes.PAYMENT_FORBIDDEN]: 403,
  [ErrorCodes.PAYMENT_INVALID_METHOD]: 400,
  [ErrorCodes.PAYMENT_INVALID_STATUS]: 400,
  [ErrorCodes.PAYMENT_INVALID_TRANSITION]: 409,
  [ErrorCodes.PAYMENT_ALREADY_EXISTS]: 409,
  [ErrorCodes.PAYMENT_AMOUNT_MISMATCH]: 409,
  [ErrorCodes.PAYMENT_EXPIRED]: 410,
  [ErrorCodes.PAYMENT_CONFLICT]: 409,
  [ErrorCodes.PAYMENT_IDEMPOTENCY_CONFLICT]: 409,
  [ErrorCodes.PAYMENT_SIGNATURE_INVALID]: 401,
  [ErrorCodes.PAYMENT_CALLBACK_INVALID]: 400,
  [ErrorCodes.PAYMENT_PROVIDER_DISABLED]: 503,
  [ErrorCodes.PAYMENT_ORDER_UNAVAILABLE]: 503,
  [ErrorCodes.PAYMENT_ORDER_NOT_PAYABLE]: 409,
  [ErrorCodes.PAYMENT_REFUND_NOT_ALLOWED]: 409,
  [ErrorCodes.PAYMENT_REFUND_EXCEEDS_PAID]: 409,
  [ErrorCodes.PAYMENT_REFUND_ALREADY_PROCESSED]: 409,
  [ErrorCodes.PAYMENT_MOCK_DISABLED]: 403,
  [ErrorCodes.RATE_LIMITED]: 429,
  [ErrorCodes.INTERNAL_ERROR]: 500,
};

export class AppError extends Error {
  readonly errorCode: ErrorCode;
  readonly details: ErrorDetails;
  readonly httpStatus: number;
  readonly traceId?: string;

  constructor(options: {
    errorCode: ErrorCode;
    message: string;
    details?: ErrorDetails;
    httpStatus?: number;
    traceId?: string;
    cause?: unknown;
  }) {
    super(options.message, { cause: options.cause });
    this.name = 'AppError';
    this.errorCode = options.errorCode;
    this.details = options.details ?? {};
    this.httpStatus =
      options.httpStatus ?? HTTP_STATUS_BY_CODE[options.errorCode] ?? 500;
    this.traceId = options.traceId;
  }
}

export function createErrorEnvelope(options: {
  errorCode: ErrorCode;
  message: string;
  details?: ErrorDetails;
  traceId: string;
  timestamp?: string;
}): ErrorEnvelope {
  return {
    errorCode: options.errorCode,
    message: options.message,
    details: options.details ?? {},
    traceId: options.traceId,
    timestamp: options.timestamp ?? new Date().toISOString(),
  };
}

export function toErrorEnvelope(
  error: unknown,
  traceId: string,
): ErrorEnvelope {
  if (error instanceof AppError) {
    return createErrorEnvelope({
      errorCode: error.errorCode,
      message: error.message,
      details: error.details,
      traceId: error.traceId ?? traceId,
    });
  }

  if (error instanceof Error) {
    return createErrorEnvelope({
      errorCode: ErrorCodes.INTERNAL_ERROR,
      message: 'Đã xảy ra lỗi hệ thống',
      details: { name: error.name },
      traceId,
    });
  }

  return createErrorEnvelope({
    errorCode: ErrorCodes.INTERNAL_ERROR,
    message: 'Đã xảy ra lỗi hệ thống',
    details: {},
    traceId,
  });
}

export function httpStatusForErrorCode(errorCode: ErrorCode): number {
  return HTTP_STATUS_BY_CODE[errorCode] ?? 500;
}
