apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nexatech.fullname" . }}-config
  labels:
    {{- include "nexatech.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  PUBLIC_STOREFRONT_URL: {{ .Values.config.publicStorefrontUrl | quote }}
  PUBLIC_ADMIN_URL: {{ .Values.config.publicAdminUrl | quote }}
  PUBLIC_API_URL: {{ .Values.config.publicApiUrl | quote }}
  POSTGRES_HOST: {{ .Values.global.postgresql.host | quote }}
  POSTGRES_PORT: {{ .Values.global.postgresql.port | quote }}
  POSTGRES_SSLMODE: {{ .Values.global.postgresql.sslMode | quote }}
  POSTGRES_POOL_MAX: {{ .Values.global.postgresql.poolMax | quote }}
  POSTGRES_CONNECT_TIMEOUT: {{ .Values.global.postgresql.connectTimeout | quote }}
